//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_Account
{
    public string acc_UserID { get; set; }
    public string acc_Password { get; set; }
    public Nullable<bool> acc_Active { get; set; }
}

public partial class tbl_CancelPolicy
{
    public tbl_CancelPolicy()
    {
        this.tbl_Package = new HashSet<tbl_Package>();
    }

    public int cnp_ID { get; set; }
    public string cnp_Name { get; set; }
    public string cnp_Description { get; set; }

    public virtual ICollection<tbl_Package> tbl_Package { get; set; }
}

public partial class tbl_Category
{
    public tbl_Category()
    {
        this.tbl_Subcategory = new HashSet<tbl_Subcategory>();
    }

    public int cat_ID { get; set; }
    public string cat_Name { get; set; }
    public string cat_Descripton { get; set; }
    public Nullable<int> cat_Priority { get; set; }
    public Nullable<bool> cat_Active { get; set; }
    public string cat_BannerImage { get; set; }
    public string cat_SquareImage { get; set; }
    public string cat_BackgroundImage1 { get; set; }
    public string cat_BackgroundImage2 { get; set; }

    public virtual ICollection<tbl_Subcategory> tbl_Subcategory { get; set; }
}

public partial class tbl_Exclusion
{
    public tbl_Exclusion()
    {
        this.tbl_Package = new HashSet<tbl_Package>();
    }

    public int exc_ID { get; set; }
    public string exc_Name { get; set; }
    public string exc_Description { get; set; }

    public virtual ICollection<tbl_Package> tbl_Package { get; set; }
}

public partial class tbl_FeaturedPackage
{
    public int ftp_ID { get; set; }
    public Nullable<int> ftp_PlaceFK { get; set; }
    public Nullable<int> ftp_Priority { get; set; }

    public virtual tbl_Package tbl_Package { get; set; }
}

public partial class tbl_Gallery
{
    public int glr_ID { get; set; }
    public string glr_Image { get; set; }
    public string glr_Description { get; set; }
    public string glr_Type { get; set; }
    public Nullable<int> glr_PlaceID { get; set; }
    public Nullable<int> glr_PackageID { get; set; }

    public virtual tbl_Package tbl_Package { get; set; }
    public virtual tbl_Place tbl_Place { get; set; }
}

public partial class tbl_Package
{
    public tbl_Package()
    {
        this.tbl_FeaturedPackage = new HashSet<tbl_FeaturedPackage>();
        this.tbl_Gallery = new HashSet<tbl_Gallery>();
        this.tbl_PlacePackage = new HashSet<tbl_PlacePackage>();
        this.tbl_Price = new HashSet<tbl_Price>();
    }

    public int pkg_ID { get; set; }
    public string pkf_Name { get; set; }
    public string pkg_Subtitle { get; set; }
    public string pkg_Overview { get; set; }
    public string pkg_Description { get; set; }
    public string pkg_Inclusion { get; set; }
    public Nullable<bool> pkg_DefaultSeason { get; set; }
    public string pkg_DefaultRoom { get; set; }
    public string pkg_DefaultDay { get; set; }
    public string pkg_DayHeading1 { get; set; }
    public string pkg_DayItinerary1 { get; set; }
    public string pkg_DayHeading2 { get; set; }
    public string pkg_DayItinerary2 { get; set; }
    public string pkg_DayHeading3 { get; set; }
    public string pkg_DayItinerary3 { get; set; }
    public string pkg_Roomtype1 { get; set; }
    public string pkg_Roomtype2 { get; set; }
    public string pkg_Roomtype3 { get; set; }
    public Nullable<int> pkg_Priority { get; set; }
    public Nullable<bool> pkg_Active { get; set; }
    public string pkg_BannerImage { get; set; }
    public string pkg_SquareImage { get; set; }
    public string pkg_BackgroundImage1 { get; set; }
    public string pkg_BackgroundImage2 { get; set; }
    public Nullable<int> pkg_ExclusionFK { get; set; }
    public Nullable<int> pkg_TermsAndConditionFK { get; set; }
    public Nullable<int> pkg_CancelPolicyFK { get; set; }
    public Nullable<int> pkg_SubcategoryFK { get; set; }

    public virtual tbl_CancelPolicy tbl_CancelPolicy { get; set; }
    public virtual tbl_Exclusion tbl_Exclusion { get; set; }
    public virtual ICollection<tbl_FeaturedPackage> tbl_FeaturedPackage { get; set; }
    public virtual ICollection<tbl_Gallery> tbl_Gallery { get; set; }
    public virtual tbl_Subcategory tbl_Subcategory { get; set; }
    public virtual tbl_TermsAndCondition tbl_TermsAndCondition { get; set; }
    public virtual ICollection<tbl_PlacePackage> tbl_PlacePackage { get; set; }
    public virtual ICollection<tbl_Price> tbl_Price { get; set; }
}

public partial class tbl_Place
{
    public tbl_Place()
    {
        this.tbl_Gallery = new HashSet<tbl_Gallery>();
        this.tbl_PlacePackage = new HashSet<tbl_PlacePackage>();
    }

    public int plc_ID { get; set; }
    public string plc_Description { get; set; }
    public string plc_TimeToVisit { get; set; }
    public string plc_Location { get; set; }
    public Nullable<int> plc_Priority { get; set; }
    public Nullable<bool> plc_Active { get; set; }
    public string plc_BannerImage { get; set; }
    public string plc_SquareImage { get; set; }
    public string plc_BackgroundImage1 { get; set; }
    public string plc_BackgroundImage2 { get; set; }
    public string plc_Name { get; set; }

    public virtual ICollection<tbl_Gallery> tbl_Gallery { get; set; }
    public virtual ICollection<tbl_PlacePackage> tbl_PlacePackage { get; set; }
}

public partial class tbl_PlacePackage
{
    public int plg_ID { get; set; }
    public int plg_PackageID { get; set; }
    public int plg_PlaceID { get; set; }

    public virtual tbl_Package tbl_Package { get; set; }
    public virtual tbl_Place tbl_Place { get; set; }
}

public partial class tbl_Price
{
    public int prc_ID { get; set; }
    public string prc_Coordinate { get; set; }
    public Nullable<int> prc_PackageId { get; set; }
    public Nullable<int> prc_Price { get; set; }

    public virtual tbl_Package tbl_Package { get; set; }
}

public partial class tbl_Subcategory
{
    public tbl_Subcategory()
    {
        this.tbl_Package = new HashSet<tbl_Package>();
    }

    public int sct_ID { get; set; }
    public string sct_Name { get; set; }
    public Nullable<int> sct_CategoryFK { get; set; }
    public string sct_Descripton { get; set; }
    public Nullable<int> sct_Priority { get; set; }
    public Nullable<bool> sct_Active { get; set; }
    public string sct_BannerImage { get; set; }
    public string sct_SquareImage { get; set; }
    public string sct_BackgroundImage1 { get; set; }
    public string sct_BackgroundImage2 { get; set; }

    public virtual tbl_Category tbl_Category { get; set; }
    public virtual ICollection<tbl_Package> tbl_Package { get; set; }
}

public partial class tbl_TermsAndCondition
{
    public tbl_TermsAndCondition()
    {
        this.tbl_Package = new HashSet<tbl_Package>();
    }

    public int tnc_ID { get; set; }
    public string tnc_Name { get; set; }
    public string tnc_Description { get; set; }

    public virtual ICollection<tbl_Package> tbl_Package { get; set; }
}

public partial class tbl_Tour
{
    public int tor_ID { get; set; }
    public string tor_Overview { get; set; }
    public string tor_Description { get; set; }
    public Nullable<int> tor_Priority { get; set; }
    public Nullable<bool> tor_Active { get; set; }
    public string tor_BannerImage { get; set; }
    public string tor_SquareImage { get; set; }
    public string tor_BackgroundImage1 { get; set; }
    public string tor_BackgroundImage2 { get; set; }
    public string tor_Name { get; set; }
}
