//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Chandan_Banjara_WorldEntities : DbContext
{
    public Chandan_Banjara_WorldEntities()
        : base("name=Chandan_Banjara_WorldEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<tbl_Account> tbl_Account { get; set; }
    public DbSet<tbl_CancelPolicy> tbl_CancelPolicy { get; set; }
    public DbSet<tbl_Category> tbl_Category { get; set; }
    public DbSet<tbl_Exclusion> tbl_Exclusion { get; set; }
    public DbSet<tbl_FeaturedPackage> tbl_FeaturedPackage { get; set; }
    public DbSet<tbl_Gallery> tbl_Gallery { get; set; }
    public DbSet<tbl_Package> tbl_Package { get; set; }
    public DbSet<tbl_Place> tbl_Place { get; set; }
    public DbSet<tbl_PlacePackage> tbl_PlacePackage { get; set; }
    public DbSet<tbl_Price> tbl_Price { get; set; }
    public DbSet<tbl_Subcategory> tbl_Subcategory { get; set; }
    public DbSet<tbl_TermsAndCondition> tbl_TermsAndCondition { get; set; }
    public DbSet<tbl_Tour> tbl_Tour { get; set; }
}
